theme: jekyll-theme-minimal
title: Xiangqi Su
description: 2nd-year grad student in Quantitative Finance at University of Michigan. 

author:
  github: XQSu

email: xiangqsu@umich.edu
linkedin: xiangqisu
